<?php

/**
 * @file
 * Contains entity_alias.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_alias_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === "help.page.entity_alias") {
    $output = '<p>' . t('Tool for redirecting entities to its aliases by id found in url.') . '</p>';
    return $output;
  }
}

/**
 * Implements hook_pathauto_alias_alter().
 */
function entity_alias_pathauto_alias_alter(&$alias, array &$context) {
  $type             = $context['type'];
  $entity_types     = \Drupal::config('entity_alias.settings')
    ->get('entity_types');
  $entity_types_ids = array_keys($entity_types);

  if (in_array($type,
      $entity_types_ids) && $entity_types[$type]['enabled'] == 1
  ) {
    $nid = $context['data']['node']->id();
    $alias .= '-' . $nid;
  }
}
