<?php

/**
 * @file
 * Installation functions for Smart alias module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_install().
 */
function entity_alias_install() {
  global $base_url;
  $url = new Url('entity_alias.entity_alias_settings_form');
  drupal_set_message(t('You will need to @configure to use with Entity Alias.', [
    '@configure' => \Drupal::l('configure the content types', $url->fromUri($base_url . '/admin/config/entity_alias/entityaliassettings')),
  ]));
}