<?php

/**
 * @file
 * Smart alias module.
 */

use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_help().
 */
function smart_alias_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.smart_alias') {
    $output = '<p>' . t('Redirecting entities to its aliases using id.') . '</p>';
    return $output;
  }
}

/**
 * Implements hook_node_insert().
 */
function smart_alias_node_insert(EntityInterface $node) {
  $types = \Drupal::config('smart_alias.settings')->get('entity_types');
  $entity_type = $node->getType();
  if (isset($types[$entity_type]) && $types[$entity_type]['enabled']) {
    $redirect = new RedirectResponse($node->label() . '-' . $node->id());
    $redirect->send();
  }
}

/**
 * Implements hook_alias_menu_local_tasks_alter().
 */
function smart_alias_menu_local_tasks_alter(&$data, $route_name) {
  if(isset($data['tabs'][0]['pathauto.patterns.form'])) {
    $data['tabs'][0]['pathauto.smart_alias'] = [
      '#theme' => 'menu_local_task',
      '#link' => [
        'title' => 'Smart alias',
        'url' => Url::fromRoute('smart_alias.settings'),
      ],
      '#weight' => 50,
    ];
  }
}
