<?php

/**
 * @file
 * Smart Alias module which takes care of redirecting to aliased path.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_help().
 */
function smart_alias_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.smart_alias') {
    $output = '<p>' . t('Redirect entities to their alias with pending node ID.') . '</p>';
    return $output;
  }
}

/**
 * Implements hook_node_insert().
 */
function smart_alias_node_insert(EntityInterface $node) {
  $types = \Drupal::config('smart_alias.settings')->get('entity_types');
  $entity_type = $node->getType();
  if (isset($types[$entity_type]) && $types[$entity_type]['enabled']) {
    $redirect = new RedirectResponse($node->label() . '-' . $node->id());
    $redirect->send();
  }
}
